
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Jan 18 16:56:26 CET 2018
//----------------------------------------------------

package com.oromis;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int LGPAR = 15;
  public static final int GE = 35;
  public static final int UMINUS = 42;
  public static final int DOUBLE_CONST = 24;
  public static final int DOUBLE = 7;
  public static final int SEMI = 4;
  public static final int INT = 5;
  public static final int MINUS = 20;
  public static final int WRITE = 18;
  public static final int AND = 40;
  public static final int NOT = 39;
  public static final int LT = 36;
  public static final int RPAR = 13;
  public static final int OR = 41;
  public static final int BOOL = 6;
  public static final int RGPAR = 16;
  public static final int COMMA = 10;
  public static final int DIV = 22;
  public static final int PLUS = 19;
  public static final int ASSIGN = 28;
  public static final int IF = 29;
  public static final int LE = 37;
  public static final int EOF = 0;
  public static final int INT_CONST = 23;
  public static final int TRUE = 26;
  public static final int error = 1;
  public static final int START = 3;
  public static final int EQ = 38;
  public static final int HEAD = 2;
  public static final int NAME = 9;
  public static final int TIMES = 21;
  public static final int COLON = 14;
  public static final int ELSE = 33;
  public static final int READ = 17;
  public static final int WHILE = 31;
  public static final int THEN = 30;
  public static final int LPAR = 12;
  public static final int STRING = 8;
  public static final int DEF = 11;
  public static final int FALSE = 27;
  public static final int STRING_CONST = 25;
  public static final int GT = 34;
  public static final int DO = 32;
}

